openapi: 3.0.0
info:
  title: Chat API
  description: Simple Chat API
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Default Spring Boot server
components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 5
        sender_id:
          type: string
          format: uuid
          example: 10
        date:
          type: string
          format: date-time
          example: 2017-07-21T17:32:28Z
        text:
          type: string
          example: Hello
      required:
        - sender_id
        - date
        - text
paths:
  /messages:
    get:
      summary: Returns a list of all messages
      responses:
        '200':
          description: A JSON array of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
    post:
      summary: Send a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '201':
          description: Sent the message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  /messages/{id}:
    patch:
      summary: Update a message
      parameters:
        - name: id
          in: path
          description: ID of message to update
          required: true
          schema:
            type: string
            format: uuid
          style: simple
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '201':
          description: Updated the message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
    delete:
      summary: Delete a message
      parameters:
        - name: id
          in: path
          description: ID of message to delete
          required: true
          schema:
            type: string
            format: uuid
          style: simple
      responses:
        '204':
          description: Deleted the message
